export enum ESortOrder {
  Asc = 'asc',
  Desc = 'desc',
}

export enum ERole {
  SUPPER = 'SUPPER',
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum EDirections {
  EAST = 'East',
  WEST = 'West',
  SOUTH = 'South',
  NORTH = 'North',
  SOUTH_EAST = 'SouthEast',
  SOUTH_WEST = 'SouthWest',
  NORTH_EAST = 'NorthEast',
  NORTH_WEST = 'NorthWest',
}

export enum EOrderStatus {
  PENDING = 'PENDING',
  SHIPPING = 'SHIPPING',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  CONFIRM = 'CONFIRM',
  PAID = 'PAID',
  DEBT = 'DEBT',
}

export enum EInventoryTransactionType {
  IMPORT = 'IMPORT',
  EXPORT = 'EXPORT',
  RETURN_DAMAGED = 'RETURN_DAMAGED',
  PRODUC_IMPORT = 'PRODUC_IMPORT',
  PRODUC_EXPORT = ' PRODUC_EXPORT',
}

export enum EPermission {
  ALL = 'ALL',
  DASHBOARD = 'DASHBOARD',
  VIEW_ORDER = 'VIEW_ORDER',
  WRITE_ORDER = 'WRITE_ORDER',
  VIEW_CUSTOMER = 'VIEW_CUSTOMER',
  WRITE_CUSTOMER = 'WRITE_CUSTOMER',
  VIEW_CUSTOM_PRICE = 'VIEW_CUSTOM_PRICE',
  WRITE_CUSTOM_PRICE = 'WRITE_CUSTOM_PRICE',
  VIEW_PRODUCT = 'VIEW_PRODUCT',
  WRITE_PRODUCT = 'WRITE_PRODUCT',
  VIEW_CATEGORY = 'VIEW_CATEGORY',
  WRITE_CATEGORY = 'WRITE_CATEGORY',
  VIEW_INVENTORY = 'VIEW_INVENTORY',
  WRITE_INVENTORY = 'WRITE_INVENTORY',
  VIEW_MISSING_PRODUCT = 'VIEW_MISSING_PRODUCT',
  WRITE_MISSING_PRODUCT = 'WRITE_MISSING_PRODUCT',
  VIEW_INVENTORY_HISTORY = 'VIEW_INVENTORY_HISTORY',
  VIEW_USER = 'VIEW_USER',
  WRITE_USER = 'WRITE_USER',
  VIEW_GENERAL_INFO = 'VIEW_GENERAL_INFO',
  WRITE_GENERAL_INFO = 'WRITE_GENERAL_INFO',
}
